### ISSUE TITLE
[Feature Request] Support git submodule repository

### ISSUE THREAD

**Issue by filzrev** [kekyo/GitReader#11]
I want to get git submodule repository information with `GitReader`
Currency it fails to get information with `Repository does not exist.` exceptions occurred at following lines.

- https://github.com/kekyo/GitReader/blob/ce68b633419a8b16d642e6ea1ec3492cdbdf2584/GitReader.Core/Primitive/PrimitiveRepositoryFacade.cs#L27-L30
- https://github.com/kekyo/GitReader/blob/ce68b633419a8b16d642e6ea1ec3492cdbdf2584/GitReader.Core/Structures/StructuredRepositoryFacade.cs#L175-L178

It's due to `.git` directory is not exist but only  exists `.git` **file** on directory that are managed by git submodule.

**Requested Features**
Is is able to support for following repository types.
- Repository that is maanaged by `git submodule`
- Repository that is created with `git init --separate-git-dir` options

These repository contains `.git` **file**. and that file contains `gitdir:` directory path.

**Additional context**
As far as I've tested. It can get git submodule information with following code modifications. 

```csharp
        if (!Directory.Exists(repositoryPath))
        {
            if (!File.Exists(repositoryPath))
            {
                throw new ArgumentException("Repository does not exist.");
            }

            // Read `git` file's `gitdir:` information
            var gitDirLine = File.ReadAllLines(repositoryPath).FirstOrDefault() ?? "";
            if (gitDirLine.StartsWith("gitdir: ", StringComparison.Ordinal))
            {
                var gitDirPath = gitDirLine.Substring("gitdir: ".Length);

                // Resolve to full path (And normalize path directory separators)
                // TODO: Relative path that starts with "~/" should be resolved (Currently it's resolved as `~/` directory) 
                repositoryPath = Path.IsPathRooted(gitDirPath)
                    ? Path.GetFullPath(gitDirPath)
                    : Path.GetFullPath(Utilities.Combine(path, gitDirPath));
            }

            // Check specified `gitdir` exists
            if (!Directory.Exists(repositoryPath))
            {
                throw new ArgumentException("Repository does not exist. `.git` file exists. But failed to `gitdir` or specified directory is not exists.");
            }
        }
```

**Comment by kekyo** [comment]
@filzrev Hi, Made changes to allow Git submodule manipulation: [feature/11](https://github.com/kekyo/GitReader/tree/feature/11)

* Handling of `.git` files as pointed out.
* In addition, it is now possible to open the repository in the case of a submodule from a given tree of commits. If you find a `TreeSubModuleEntry` class as follows, you can open it as a separate repository with the `OpenSubModuleAsync()` method:
  ```csharp
    [Test]
    public async Task OpenSubModule()
    {
        using var repository = await Repository.Factory.OpenStructureAsync(
            RepositoryTestsSetUp.GetBasePath("test4"));

        var commit = await repository.GetCommitAsync(
            "37021d38937107d5782f063f78f502f2da14c751");

        var tree = await commit!.GetTreeRootAsync();

        var subModule = tree.Children.OfType<TreeSubModuleEntry>().
            First(child => child.Name == "GitReader");

        using var subModuleRepository = await subModule.OpenSubModuleAsync();

        var subModuleCommit = await subModuleRepository.GetCommitAsync(
            subModule.Hash);

        await Verifier.Verify(subModuleCommit);
    }
  ```
* I think you actually have to recursively process [samples/gitexport](https://github.com/kekyo/GitReader/pull/13/commits/d71bc8077010ab1e0c0d54774a174790934b66f8#diff-8eefb34c7ac4f96c006a88ceb38ab08476d6fa3732b6b9404a08940624561978) shows an example of such an operation.

Does such an interface serve your purpose? If it looks rough and good, I would like to put it out.

**Comment by kekyo** [comment]
d199c32cb9162a3b6307e6e6c32732ea9799d2bc : Improves redirection `gitdir:` directive on `.git` file with home directory resolver.

**Comment by filzrev** [comment]
Thanks for responding to my feature request.
I have confirmed that it can get git submodule information as expected.
